### ISSUE TITLE
Charts occasionally not rendering

### ISSUE THREAD

**Issue by edbentinck** [theborakompanioni/angular-keenio#1]
There seems to be an intermittent bug where the charts don't always render. The bug can be reproduced when refreshing the angular-keenio demo a few times.

My hunch is that it is an issue involving the `$digest` loop, or `$evalAsync` – particularly because this bug becomes far more apparent in apps with complex DOM structure (i.e. more `$watch`es). I'm not very experienced working with $digest though, so I'm unsure on how to solve it.

Any ideas? Maybe it's not even anything to do with that?..

**Comment by theborakompanioni** [comment]
Thanks for bringing this to my attention @edbentinck 
I could reproduce the problem.. it seems `Keen` has not finished loading its dependencies.
A quick solution would be to bootstrap the application manually e.g.
```
<script>
  angular.element(document).ready(function () {
    Keen.ready(function () {
      angular.bootstrap(document, ['myApp']);
    });
  });
</script>
```
Hope this approach is applicable for you.
I have also included this snippet in the README file. Thank you very much!
