### ISSUE TITLE
Demo page issue

### ISSUE THREAD

**Issue by Abhith** [theborakompanioni/angular-keenio#4]
Demo page not working. All the section in the demo page says "**Origin is not allowed by Access-Control-Allow-Origin**".

**Comment by theborakompanioni** [comment]
Hey @Abhith!

It's working for me. May it be the case that you have an adblocker enabled?

**Comment by Abhith** [comment]
@theborakompanioni oh, yes. It worked after disabling adblocker. Thanks.
